// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mobile/data/model/address/address_model.dart';
import 'package:mobile/data/model/history/history_model.dart';
import 'package:mobile/data/model/order/order_draft.dart';
import 'package:mobile/data/model/review/review_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(OrderDraftAdapter());
    registerAdapter(ReviewModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(HistoryModelAdapter());
    registerAdapter(OrderDraftAdapter());
    registerAdapter(ReviewModelAdapter());
  }
}
